# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# jobs key
jobs:
# A job named as "dredd"
  dredd:
 # define where the source code will run in docker
    docker:
    # define the running environment
      - image: 'circleci/node:12'
 # define the actrual work steps
    steps:
    # checkout is similar as "git clone", for get the code to execute. 
      - checkout
      - run: npm install dredd@13.1.2 --global
      - run: dredd
      
# define the workflows key
workflows:
# define one name for this workflows with build_test
  build_test:
  # under the workflows, needs the jobs 
    jobs:
      - dredd
    
